//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDM.WebUI {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDM.WebUI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Achievement.
        /// </summary>
        public static string Assignment_Achievement {
            get {
                return ResourceManager.GetString("Assignment.Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complexity.
        /// </summary>
        public static string Assignment_Complexity {
            get {
                return ResourceManager.GetString("Assignment.Complexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DateEnd.
        /// </summary>
        public static string Assignment_DateEnd {
            get {
                return ResourceManager.GetString("Assignment.DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DateRegistered.
        /// </summary>
        public static string Assignment_DateRegistered {
            get {
                return ResourceManager.GetString("Assignment.DateRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Assignment_Description {
            get {
                return ResourceManager.GetString("Assignment.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Implement.
        /// </summary>
        public static string Assignment_Implement {
            get {
                return ResourceManager.GetString("Assignment.Implement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Assignment_Name {
            get {
                return ResourceManager.GetString("Assignment.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OwnAchievement.
        /// </summary>
        public static string Assignment_OwnAchievement {
            get {
                return ResourceManager.GetString("Assignment.OwnAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OwnComplexity.
        /// </summary>
        public static string Assignment_OwnComplexity {
            get {
                return ResourceManager.GetString("Assignment.OwnComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parent.
        /// </summary>
        public static string Assignment_Parent {
            get {
                return ResourceManager.GetString("Assignment.Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Begin.
        /// </summary>
        public static string UI_Begin {
            get {
                return ResourceManager.GetString("UI.Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complete.
        /// </summary>
        public static string UI_Complete {
            get {
                return ResourceManager.GetString("UI.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Task.
        /// </summary>
        public static string UI_CreateTask {
            get {
                return ResourceManager.GetString("UI.CreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Task.
        /// </summary>
        public static string UI_DeleteButton {
            get {
                return ResourceManager.GetString("UI.DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string UI_Loading {
            get {
                return ResourceManager.GetString("UI.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resume.
        /// </summary>
        public static string UI_Resume {
            get {
                return ResourceManager.GetString("UI.Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string UI_Stop {
            get {
                return ResourceManager.GetString("UI.Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assigned.
        /// </summary>
        public static string WorkStatus_Assigned {
            get {
                return ResourceManager.GetString("WorkStatus.Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completed.
        /// </summary>
        public static string WorkStatus_Completed {
            get {
                return ResourceManager.GetString("WorkStatus.Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InProgress.
        /// </summary>
        public static string WorkStatus_InProgress {
            get {
                return ResourceManager.GetString("WorkStatus.InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopped.
        /// </summary>
        public static string WorkStatus_Stopped {
            get {
                return ResourceManager.GetString("WorkStatus.Stopped", resourceCulture);
            }
        }
    }
}
